builds:
- id: "locomoco"
  binary: locomoco
  goos:
  - linux
  - darwin
  goarch:
  - amd64
checksum:
  name_template: 'checksums.txt'
dist: ./dist
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: faceyacc
    name: locomoco
brews:
- tap:
    owner: faceyacc
    name: homebrew-tools
  name: locomoco
  homepage: "https://github.com/faceyacc/locomoco"
  description: "A simple GitHub contribution and repo viewer."
  folder: Formula
  install: |
    bin.install "locomoco"